jobs:
  - job: DeployStreamlitApp
    displayName: Deploy Streamlit App to Azure Container Instances
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: "3.12"
          addToPath: true
          architecture: x64

      - task: Bash@3
        inputs:
          targetType: inline
          script: |
            python -m venv venv
            source venv/bin/activate
            pip install --upgrade pip
            pip install azure-cli azureml-sdk[cli]
            # Install specific version of Azure CLI
            pip install azure-cli==2.20.0

            # Upgrade Azure ML SDK
            pip install ruamel.yaml
            # Install pytest and pytest-cov for testing
            pip install pytest pytest-cov
            pip install streamlit transformers torch

      - task: AzureCLI@2
        inputs:
          azureSubscription: nlp_cicd
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            source venv/bin/activate
            az extension add -n ml --version 2.25.0 --allow-preview

            # Set variables for the model and endpoint
            endpoint_name="streamlit-endpoint"
            model_uri="azureml://subscriptions/a22eeea6-98d6-4951-a80c-326264b6750f/resourceGroups/my-ml-resource-group/workspaces/my-ml-workspace/datastores/workspaceblobstore/paths/LocalUpload/218cca5e53b658f006af17f0096a8f66/models"

            # Create the endpoint
            az ml online-endpoint update --name $endpoint_name \
              --resource-group $(ml.resourceGroup) \
              --workspace-name $(ml.workspace)

      - task: AzureCLI@2
        inputs:
          azureSubscription: nlp_cicd
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            # Activate virtual environment
            source venv/bin/activate

            # Set variables
            environment_name="azureml:env_cicd3:1"
            scoring_script="score.py"
            condafile="conda.yaml"
            instance_count=1
            cpu_allocation=1
            memory_allocation=0.5
            endpoint_name="streamlit-endpoint"
            model_path="azureml:transformer_cicd:19"
            instance_type="Standard_DS3_v2"

            # Confirm Azure CLI login
            echo "Verifying Azure CLI login..."
            az account show > /dev/null 2>&1
            if [ $? -ne 0 ]; then
              echo "Azure CLI is not logged in. Please check your service connection."
              exit 1
            fi

            # Create the deploy.yml file dynamically
            echo "Creating deploy.yml file..."
            cat <<EOF > ./deploy.yml
            \$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
            command: >-
              python $scoring_script
            name: streamlit-deployment
            environment:
              conda_file: conda.yaml
              image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04
            code: ./  # Path to the application code directory
            inputs:
              model_path:
                type: uri_folder
                path: $model_path
            resources:
              instance_count: $instance_count
            EOF

            # Output message to show the generated file
            echo "deploy.yml file has been generated."

            # Submit the job using az ml job create
            echo "Submitting the job using az ml job create..."
            az ml job create --file ./deploy.yml \
              --resource-group my-ml-resource-group \
              --workspace-name my-ml-workspace

          