name: streamlit_app_env
channels:
  - defaults
  - conda-forge
dependencies:
  # Specify the Python interpreter version
  - python=3.12.4
  - pip>=19.1.1
  - numpy>=1.13.3
  - pandas==0.25.1
  - pytest>=3.6.4
  - pip:
      - azureml-sdk==1.0.23
      - ruamel.yaml
      - torch
      - transformers
      - streamlit
      - protobuf<4.22  # Prevent protobuf compatibility issues with Streamlit
